
package com.ys.wx.service.deptandperson;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "IQueryInfoWXServicePortType", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IQueryInfoWXServicePortType {


    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetDeptWXAll", action = "urn:GetDeptWXAll")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDeptWXAll", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService", className = "com.demo.client.GetDeptWXAll")
    @ResponseWrapper(localName = "GetDeptWXAllResponse", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService", className = "com.demo.client.GetDeptWXAllResponse")
    public String getDeptWXAll();

    /**
     * @param startTime
     * @param index
     * @param operate
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetPsndocsByTimeAndStatusWX", action = "urn:GetPsndocsByTimeAndStatusWX")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetPsndocsByTimeAndStatusWX", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService", className = "com.demo.client.GetPsndocsByTimeAndStatusWX")
    @ResponseWrapper(localName = "GetPsndocsByTimeAndStatusWXResponse", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService", className = "com.demo.client.GetPsndocsByTimeAndStatusWXResponse")
    public String getPsndocsByTimeAndStatusWX(
            @WebParam(name = "startTime", targetNamespace = "")
                    String startTime,
            @WebParam(name = "operate", targetNamespace = "")
                    Integer operate,
            @WebParam(name = "index", targetNamespace = "")
                    Integer index);

}
