
package com.ys.wx.service.data.ehr;

import com.mhome.tools.common.ReadProperty;
import com.mhome.tools.common.SpringContextHolder;
import com.ys.wx.constant.WxConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "IQueryInfoWXService", targetNamespace = "http://idm.ys.itf.nc/IQueryInfoWXService", wsdlLocation = "http://10.10.20.1/uapws/service/nc.itf.ys.idm.IQueryInfoWXService?wsdl")
public class IQueryInfoWXService extends Service {

    private final static URL IQUERYINFOWXSERVICE_WSDL_LOCATION;
    private final static Logger       logger       = Logger.getLogger(IQueryInfoWXService.class.getName());
    private final static ReadProperty readProperty = SpringContextHolder.getBean("readProperty");

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IQueryInfoWXService.class.getResource(".");
            url = new URL(baseUrl, "http://" + readProperty.getValue(WxConstant.EHR_DB_SERVICE_IP) + "/uapws/service/nc.itf.ys.idm.IQueryInfoWXService?wsdl");
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>webService 接口地址>>>>>>>>>>>>>>>>>>>>>>\nhttp://" + readProperty.getValue(WxConstant.EHR_DB_SERVICE_IP) + "/uapws/service/nc.itf.ys.idm.IQueryInfoWXService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.20.1/uapws/service/nc.itf.ys.idm.IQueryInfoWXService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IQUERYINFOWXSERVICE_WSDL_LOCATION = url;
    }

    public IQueryInfoWXService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IQueryInfoWXService() {
        super(IQUERYINFOWXSERVICE_WSDL_LOCATION, new QName("http://idm.ys.itf.nc/IQueryInfoWXService", "IQueryInfoWXService"));
    }

    /**
     * @return returns IQueryInfoWXServicePortType
     */
    @WebEndpoint(name = "IQueryInfoWXServiceSOAP11port_http")
    public IQueryInfoWXServicePortType getIQueryInfoWXServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://idm.ys.itf.nc/IQueryInfoWXService", "IQueryInfoWXServiceSOAP11port_http"), IQueryInfoWXServicePortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IQueryInfoWXServicePortType
     */
    @WebEndpoint(name = "IQueryInfoWXServiceSOAP11port_http")
    public IQueryInfoWXServicePortType getIQueryInfoWXServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://idm.ys.itf.nc/IQueryInfoWXService", "IQueryInfoWXServiceSOAP11port_http"), IQueryInfoWXServicePortType.class, features);
    }

}
